name: CloudStream Compiler
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.jpg"
      - "**/*.png"

jobs:
  CloudStreamCompiler:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout src
        uses: actions/checkout@v6
        with:
          path: src

      - name: Checkout builds
        uses: actions/checkout@v6
        with:
          ref: builds
          path: builds

      - name: Clean builds
        run: rm -rf $GITHUB_WORKSPACE/builds/*

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make --continue || true
          find . -name "*.cs3" -exec cp {} $GITHUB_WORKSPACE/builds/ \;

      - name: Generate plugins.json
        run: python3 $GITHUB_WORKSPACE/src/.github/scripts/gen_plugins.py

      - name: Push
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "${{ github.sha }} Derlemesi" || git commit -m "${{ github.sha }} Derlemesi" || true
          git push --force origin builds
